export enum DealState {
    NEW = 'NEW',
    CONTACTED = 'CONTACTED',
    QUALIFIED = 'QUALIFIED',
    PROPOSAL_SENT = 'PROPOSAL_SENT',
    NEGOTIATION = 'NEGOTIATION',
    WON = 'WON',
    LOST = 'LOST',
}

export enum DealEvent {
    INITIATE_CONTACT = 'INITIATE_CONTACT',
    QUALIFY_LEAD = 'QUALIFY_LEAD',
    SEND_PROPOSAL = 'SEND_PROPOSAL',
    BEGIN_NEGOTIATION = 'BEGIN_NEGOTIATION',
    ACCEPT_TERMS = 'ACCEPT_TERMS',
    REJECT_TERMS = 'REJECT_TERMS',
}
